Project1/Project1.WebUi/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Project1.WebUi.Models;
using Project1.DataAccess;
using Project1.DataAccess.Repositories.Interfaces;
using Project1.WebUi.Models.ViewModels;

namespace Project1.WebUi.Controllers
{
    public class CustomersController : Controller
    {
        private ICustomerRepository Repository { get; set; }

        public CustomersController(ICustomerRepository repository)
        {
            Repository = repository;
        }

        // GET: Customer
        public ActionResult Index()
        {
            return View(Mapper.Map< IEnumerable<Customers>, IEnumerable<Customer>>((IEnumerable<Customers>)Repository.GetAll()));
            //return View(Repository.GetAll());
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            Customer customer = Mapper.Map<Customers, Customer>(Repository.GetById(id));
            if (customer != null)
            {
                return View(customer);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerAddressForm model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Customer customer = model.Customer;
                    model.Address.DefaultAddress = true;
                    customer.Addresses = new List<Address>() { model.Address };
                    

                    Customers customerDataAccess = Mapper.Map<Customer, Customers>(customer);
                    customerDataAccess.Addresses = Mapper.Map<ICollection<Address>, ICollection<Addresses>>(customer.Addresses);

                    Repository.Save(customerDataAccess);
                    Repository.SaveChanges();
                }
                else
                {
                    return View();
                }

                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError("Stock", ex.Message);
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int id)
        {
            Customer customer = Mapper.Map<Customers, Customer> (Repository.GetById(id));
            if (customer != null)
            {
                return View(customer);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Customer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Customer customer)
        {
            try
            {
                if (id != customer.Id)
                {
                    ModelState.AddModelError("id", "should match the route id");
                    return View();
                }

                if (ModelState.IsValid)
                {
                    Repository.Save(Mapper.Map<Customer, Customers>(customer), id);
                    Repository.SaveChanges();
                }
                else
                {
                    // get a new Edit page, but with the current ModelState errors.
                    return View();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int id)
        {
            var customer = Mapper.Map<Customers, Customer>(Repository.GetById(id));
            if (customer != null)
            {
                return View(customer);
            }

            return RedirectToAction(nameof(Index));
        }

        // POST: Customer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Repository.Delete(id);
                Repository.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                throw e;
            }
        }
        
        // POST: Customer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(Search search)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    List<Customer> customers = new List<Customer>();

                    if (search.searchText == "" || search.searchText == null)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    if (search.searchBy == "ID")
                    {
                        int id = int.Parse(search.searchText);

                        Customer customer = Mapper.Map<Customers, Customer>(Repository.GetById(id));
                        customers.Add(customer);

                        return View("Index", customers);
                    }
                    else if (search.searchBy == "Name")
                    {
                        customers = Mapper.Map<List<Customers>, List<Customer>>((List<Customers>)Repository.GetByName(search.searchText));
                    }

                    return View("Index", customers);
                }
            }
            catch(Exception e)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Project1/Project1.WebUi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project1.WebUi.Models;

namespace Project1.WebUi.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project1/Project1.WebUi/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Project1.WebUi.Models;
using Project1.DataAccess;
using Project1.DataAccess.Repositories.Interfaces;
using Project1.WebUi.Models.ViewModels;
using System.Globalization;
using Project1.WebUi.Controllers.Exceptions;

namespace Project1.WebUi.Controllers
{
    public class OrdersController : Controller
    {
        private IOrderRepository Repository { get; set; }
        private ICustomerRepository CustomerRepository { get; set; }
        private IPizzaRepository PizzaRepository { get; set; }

        public OrdersController(IOrderRepository repository, ICustomerRepository customerRepository, IPizzaRepository pizzaRepository)
        {
            Repository = repository;
            CustomerRepository = customerRepository;
            PizzaRepository = pizzaRepository;
        }

        // GET: Order
        public ActionResult Index()
        {
            return View(Mapper.Map< IEnumerable<Orders>, IEnumerable<Order>>((IEnumerable<Orders>)Repository.GetAll()));
            //return View(Repository.GetAll());
        }

        // GET: Order/Details/5
        public ActionResult Details(int id)
        {
            Order order = Mapper.Map<Orders, Order>(Repository.GetById(id));
            if (order != null)
            {
                return View(order);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            IEnumerable<Customer> customerList = Mapper.Map<IEnumerable<Customers>, IEnumerable<Customer>>((IEnumerable<Customers>)CustomerRepository.GetAll());
            IEnumerable<Pizza> pizzaList = Mapper.Map<IEnumerable<Pizzas>, IEnumerable<Pizza>>((IEnumerable<Pizzas>)PizzaRepository.GetAll());
            OrderForm orderViewForm = new OrderForm(customerList, pizzaList);

            return View(orderViewForm);
        }

        // POST: Order/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                DateTime lastOrderDate = Repository.getLastOrderDate(int.Parse(collection["AddressId"]));

                Order order = new Order();

                order.CustomerId = int.Parse(collection["CustomerId"]);
                order.AddressId = int.Parse(collection["AddressId"]);
                order.Date = DateTime.Parse(collection["Date"]);
                order.Value = 0;

                order.canOrderFromSameAddress(lastOrderDate);

                IList<Pizza> pizzasList = Mapper.Map<IList<Pizzas>, IList<Pizza>>((IList<Pizzas>)PizzaRepository.GetAll());

                for (var i = 0; i<pizzasList.Count(); i++)
                {
                    int quantity = int.Parse(collection["pizzas"][i]);

                    for(var j=0; j<quantity; j++)
                    {
                        Pizza pizza = pizzasList[i];

                        //Check Stock 
                        //Need this assign because the pizzaslist doesn't get all ingredients, (it's used in other places, and don't need the ingredients)
                        Pizza check = Mapper.Map<Pizzas, Pizza>(PizzaRepository.GetById(pizza.Id));
                        check.checkStock(1);

                        order.AddPizza(pizza);
                        PizzaRepository.DecreaseStock(Mapper.Map<Pizza, Pizzas>(pizza));
                    }
                }

                Repository.Save(Mapper.Map<Order, Orders>(order));
                Repository.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (MinimumStockException ex)
            {
                ModelState.AddModelError("ErrorPizzas", ex.Message);
                return View();
            }
            catch (SamePlaceException ex)
            {
                ModelState.AddModelError("AddressId", ex.Message);
                return View();
            }
            catch (MaximumAmountException ex)
            {
                ModelState.AddModelError("Value", ex.Message);
                return View();
            }
            catch (MaximumQuantityException ex)
            {
                ModelState.AddModelError("ErrorPizzas", ex.Message);
                return View();
            }
            catch (Exception e)
            {
                ModelState.AddModelError("ErrorPizzas", e.Message);
                return View();
            }
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int id)
        {
            Order order = Mapper.Map<Orders, Order> (Repository.GetById(id));
            if (order != null)
            {
                IEnumerable<Customer> customerList = Mapper.Map<IEnumerable<Customers>, IEnumerable<Customer>>((IEnumerable<Customers>)CustomerRepository.GetAll());
                IEnumerable<Pizza> pizzaList = Mapper.Map<IEnumerable<Pizzas>, IEnumerable<Pizza>>((IEnumerable<Pizzas>)PizzaRepository.GetAll());
                OrderForm orderViewForm = new OrderForm(order, customerList, pizzaList);

                return View(orderViewForm);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Order/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                //if (ModelState.IsValid)
                //{
                    Order order = Mapper.Map<Orders, Order>(Repository.GetById(id));

                    if (id != order.Id)
                    {
                        ModelState.AddModelError("id", "should match the route id");
                        return View();
                    }

                    order.CustomerId = int.Parse(collection["CustomerId"]);
                    order.AddressId = int.Parse(collection["AddressId"]);
                    order.OrderPizzas = new List<OrderPizza>();
                    order.Value = 0;

                    IList<Pizza> pizzasList = Mapper.Map<IList<Pizzas>, IList<Pizza>>((IList<Pizzas>)PizzaRepository.GetAll());

                    for (var i = 0; i < pizzasList.Count(); i++)
                    {
                        int quantity = int.Parse(collection["pizzas"][i]);

                        for (var j = 0; j < quantity; j++)
                        {
                            order.AddPizza(pizzasList[i]);
                        }
                    }

                    Orders orderDataAccess = Mapper.Map<Order, Orders>(order);
                    orderDataAccess.OrderPizzas = Mapper.Map<ICollection<OrderPizza>, ICollection<OrderPizzas>>(order.OrderPizzas);

                    Repository.Save(orderDataAccess, id);
                    Repository.SaveChanges();
                //}
                //else
                //{
                //    // get a new Edit page, but with the current ModelState errors.
                //    return View();
                //}

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int id)
        {
            var order = Mapper.Map<Orders, Order>(Repository.GetById(id));
            if (order != null)
            {
                return View(order);
            }

            return RedirectToAction(nameof(Index));
        }

        // POST: Order/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Repository.Delete(id);
                Repository.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                throw e;
            }
        }

        //GET: Orders/CanOrderFromSameAddress/5
        public bool CanOrderFromSameAddress(int id)
        {
            try
            {
                DateTime lastOrderDate = Repository.getLastOrderDate(id);
                Order order = new Order();

                return order.canOrderFromSameAddress(lastOrderDate);
            }
            catch
            {
                return false;
            }
        }



        // POST: Order/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(Search search)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    List<Order> orders = new List<Order>();

                    if (search.searchText == "" || search.searchText == null)
                    {
                        orders = Mapper.Map<List<Orders>, List<Order>>((List<Orders>)Repository.GetAll());
                    }
                    else
                    {
                        if (search.searchBy == "ID")
                        {
                            int id = int.Parse(search.searchText);

                            Order order = Mapper.Map<Orders, Order>(Repository.GetById(id));
                            orders = new List<Order>();
                            orders.Add(order);
                        }
                        else if (search.searchBy == "Name")
                        {
                            orders = Mapper.Map<List<Orders>, List<Order>>((List<Orders>)Repository.GetByName(search.searchText));
                        }
                    }

                    switch (search.order)
                    {
                        case 1:
                            orders = orders.OrderBy(m => m.Date).ToList();
                            break;
                        case 2:

Project1/Project1.WebUi/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project1.DataAccess.Repositories.Interfaces;
using Project1.WebUi.Models.ViewModels;

namespace Project1.WebUi.Controllers
{
    public class ReportsController : Controller
    {
        private IOrderRepository orderRepository;

        public ReportsController(IOrderRepository orderRepository)
        {
            this.orderRepository = orderRepository;
        }

        public IActionResult Index()
        {
            Reports reports = new Reports();
            reports.TotalOfDay = GetTotalOfDay();

            return View(reports);
        }

        private decimal GetTotalOfDay()
        {
            DateTime dayString = DateTime.Today;
            return orderRepository.GetTotalOfDay(dayString);
        }
    }
}

Project1/Project1.WebUi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12 text-center my-3">
        <h1>Welcome</h1>
    </div>

    <!--Customers-->
    <div class="col-md-4 mt-3">
        <div class="card text-dark customers">
            <div class="card-header text-center">
                <i class="fas fa-users fa-lg mr-1"></i> Customers
            </div>
            <div class="card-body">
                <ul>
                    <li>
                        <a asp-area="" asp-controller="Customers" asp-action="Create">
                            New
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Customers" asp-action="Index">
                            Show all
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!--Addresses-->
    <div class="col-md-4 mt-3">
        <div class="card text-dark addresses">
            <div class="card-header text-center">
                <i class="fas fa-map-marked-alt fa-lg mr-1"></i>Addresses
            </div>
            <div class="card-body">
                <ul>
                    <li>
                        <a asp-area="" asp-controller="Addresses" asp-action="Create">
                            New
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Addresses" asp-action="Index">
                            Show all
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!--Pizzas-->
    <div class="col-md-4 mt-3">
        <div class="card text-dark pizzas">
            <div class="card-header text-center">
                <i class="fas fa-chart-pie fa-lg mr-1"></i> Pizzas
            </div>
            <div class="card-body">
                <ul>
                    <li>
                        <a asp-area="" asp-controller="Pizzas" asp-action="Create">
                            New
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Pizzas" asp-action="Index">
                            Show all
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!--Ingredients-->
    <div class="col-md-4 mt-3">
        <div class="card text-dark ingredients">
            <div class="card-header text-center">
                <i class="fas fa-star fa-lg mr-1"></i> Ingredients
            </div>
            <div class="card-body">
                <ul>
                    <li>
                        <a asp-area="" asp-controller="Ingredients" asp-action="Create">
                            New
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Ingredients" asp-action="Index">
                            Show all
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!--Orders-->
    <div class="col-md-4 mt-3">
        <div class="card text-dark orders">
            <div class="card-header text-center">
                <i class="fas fa-receipt fa-lg mr-1"></i> Orders
            </div>
            <div class="card-body">
                <ul>
                    <li>
                        <a asp-area="" asp-controller="Orders" asp-action="Create">
                            New
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Orders" asp-action="Index">
                            Show all
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!--Reports-->
    <div class="col-md-4 mt-3">
        <div class="card text-dark reports">
            <div class="card-header text-center">
                <i class="fas fa-chart-line fa-lg mr-1"></i>Reports
            </div>
            <div class="card-body">
                <ul>
                    <li>
                        <a asp-area="" asp-controller="Reports" asp-action="Index">
                            Show all
                        </a><br /><br />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>